# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Vito Bellini
email: v.bellini@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Applied Scientist.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://vitobellini.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: vitobellini
github_username:  vitobellini

header_pages:
  - publications.md
  - about.md

# Build settings
markdown: kramdown

minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    twitter: vitobellini
    github:  vitobellini
    rss: rss
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    linkedin: vitobellini
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll

theme: minima

plugins:
  - jekyll-feed
  - jekyll-sitemap
  
google_analytics: UA-50307526-9

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
